// <auto-generated />
using System;
using MailVerifier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailVerifier.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331194128_AddRetestTracking")]
    partial class AddRetestTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MailVerifier.Web.Models.JobEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobEmails");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedEmails")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEmails")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadedByUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VerificationJobs");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DomainExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasMxRecords")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MailboxExists")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("OriginalDomainExists")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("OriginalHasMxRecords")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("OriginalMailboxExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.JobEmail", b =>
                {
                    b.HasOne("MailVerifier.Web.Models.VerificationJob", "Job")
                        .WithMany("JobEmails")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationResult", b =>
                {
                    b.HasOne("MailVerifier.Web.Models.VerificationJob", "Job")
                        .WithMany("Results")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationJob", b =>
                {
                    b.Navigation("JobEmails");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
