// <auto-generated />
using System;
using MailVerifier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailVerifier.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927134213_RetestQueueCatchAllAndLowercaseEmails")]
    partial class RetestQueueCatchAllAndLowercaseEmails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailVerifier.Web.Models.JobEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "EmailAddress");

                    b.ToTable("JobEmails");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Response")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("RecipientId", "RecordedAt");

                    b.ToTable("SoftFailureEvents");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("LastSeenAt");

                    b.ToTable("SoftFailureRecipients");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureUploadBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FailureRowsRecorded")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RecipientRemovals")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessRowsApplied")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedByName")
                        .HasColumnType("text");

                    b.Property<string>("UploadedByUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.ToTable("SoftFailureUploadBatches");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProcessedEmails")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalEmails")
                        .HasColumnType("integer");

                    b.Property<string>("UploadedByName")
                        .HasColumnType("text");

                    b.Property<string>("UploadedByUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UploadedByUser", "CreatedAt");

                    b.ToTable("VerificationJobs");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DomainExists")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasMxRecords")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCatchAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPotentialSoftFailure")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRetested")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<bool>("MailboxExists")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OriginalDomainExists")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OriginalHasMxRecords")
                        .HasColumnType("boolean");

                    b.Property<bool?>("OriginalMailboxExists")
                        .HasColumnType("boolean");

                    b.Property<bool>("PendingRetest")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpLog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoftFailureNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("JobId", "EmailAddress")
                        .IsUnique();

                    b.HasIndex("JobId", "VerifiedAt");

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.JobEmail", b =>
                {
                    b.HasOne("MailVerifier.Web.Models.VerificationJob", "Job")
                        .WithMany("JobEmails")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureEvent", b =>
                {
                    b.HasOne("MailVerifier.Web.Models.SoftFailureRecipient", "Recipient")
                        .WithMany("Events")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailVerifier.Web.Models.SoftFailureUploadBatch", "UploadBatch")
                        .WithMany("Events")
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationResult", b =>
                {
                    b.HasOne("MailVerifier.Web.Models.VerificationJob", "Job")
                        .WithMany("Results")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureRecipient", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.SoftFailureUploadBatch", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MailVerifier.Web.Models.VerificationJob", b =>
                {
                    b.Navigation("JobEmails");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
